// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8DAsbdK7xxnybqi3eneJ5nd9jleRr97o',
    appId: '1:67468978347:web:78f922a9c23b635b696fee',
    messagingSenderId: '67468978347',
    projectId: 'projet-pfe-2852c',
    authDomain: 'projet-pfe-2852c.firebaseapp.com',
    storageBucket: 'projet-pfe-2852c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVmi6h1LauAz0zQa8Cx6xhftcYfJfrJ_Y',
    appId: '1:67468978347:android:32659903aa9796cb696fee',
    messagingSenderId: '67468978347',
    projectId: 'projet-pfe-2852c',
    storageBucket: 'projet-pfe-2852c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNqy4qbjY-l9oUj81qYdI0pKq9Arx87o',
    appId: '1:67468978347:ios:aacaa87804d4c462696fee',
    messagingSenderId: '67468978347',
    projectId: 'projet-pfe-2852c',
    storageBucket: 'projet-pfe-2852c.appspot.com',
    androidClientId: '67468978347-o2mt8vll8ti9bb2dcmigpibt8qtfj3e6.apps.googleusercontent.com',
    iosClientId: '67468978347-fq0o0rmbda2ohfmdqki65iso6gufvb3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqNqy4qbjY-l9oUj81qYdI0pKq9Arx87o',
    appId: '1:67468978347:ios:aacaa87804d4c462696fee',
    messagingSenderId: '67468978347',
    projectId: 'projet-pfe-2852c',
    storageBucket: 'projet-pfe-2852c.appspot.com',
    androidClientId: '67468978347-o2mt8vll8ti9bb2dcmigpibt8qtfj3e6.apps.googleusercontent.com',
    iosClientId: '67468978347-fq0o0rmbda2ohfmdqki65iso6gufvb3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
