// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKajimmU83zZoKxaKJ4dY-yk3ja8sjV8w',
    appId: '1:370761910382:android:c3880211f3b87d997b3e7f',
    messagingSenderId: '370761910382',
    projectId: 'carloc-a2019',
    storageBucket: 'carloc-a2019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRVMr8aMt9KIWf1GHGpdYai5Lrjw4I1AQ',
    appId: '1:370761910382:ios:9e24094482b749b67b3e7f',
    messagingSenderId: '370761910382',
    projectId: 'carloc-a2019',
    storageBucket: 'carloc-a2019.appspot.com',
    androidClientId: '370761910382-4jj0ia0766soqenj1uflnoathic2rqsu.apps.googleusercontent.com',
    iosClientId: '370761910382-g1o62t5f5fs79sfae4kdbssr389qol26.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
